image: archlinux
packages:
  - python
  - python-pip
  - wget
  - tar
  - gzip
  - xz
  - base-devel

environment:
  PYTONGUE_LOG: /tmp/pytongue.log
  FORCE_COLOR: "1"
  ZIG_VERSION: 0.14.0


tasks:

  - setup: |
      export ZIG_TARGET="linux-x86_64"
      wget "https://ziglang.org/download/${ZIG_VERSION}/zig-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz"
      sudo mkdir -p /usr/local/lib/zig-${ZIG_VERSION}
      sudo tar -xf "zig-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz" -C /usr/local/lib/zig-${ZIG_VERSION}/ --strip-components=1
      sudo ln -sf /usr/local/lib/zig-${ZIG_VERSION}/zig /usr/local/bin/zig
      rm "zig-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz"
      zig version

  - build: |
      cd Pytongue
      zig build
      ls -l zig-out/bin

  - install_python_deps: |
      cd Pytongue
      python -m pip install . --user --break-system-packages

  - test: |
      cd Pytongue
      export PYTONGUE_TEST_BINARY="${PWD}/zig-out/bin/pytongue"
      echo "Test binary path: ${PYTONGUE_TEST_BINARY}"
      test -x "${PYTONGUE_TEST_BINARY}" || (echo "Test binary not found or not executable!" && exit 1)
      export PATH=$PATH:/home/build/.local/bin
      pytest tests/e2e

  - show_logs: |
      echo "=== Test Logs (${PYTONGUE_LOG}) ==="
      if [ -f "${PYTONGUE_LOG}" ]; then
        cat "${PYTONGUE_LOG}"
      else
        echo "Log file ${PYTONGUE_LOG} not found."
      fi
