variables:
  PYTONGUE_LOG: /tmp/pytongue.log
  BUILD_DIR: zig-out/bin
  FORCE_COLOR: 1

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
      changes:
        - "src/**/*"
        - "tests/**/*"
        - "build.zig"
        - "build.zig.zon"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      changes:
        - "src/**/*"
        - "tests/**/*"
        - "build.zig"
        - "build.zig.zon"
    - if: $CI_PIPELINE_SOURCE == "web"

build-and-test:
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y curl python3 python3-pip
    - curl -L https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz | tar xJ
    - mv zig-linux-x86_64-0.13.0 /usr/local/zig
    - export PATH="/usr/local/zig:$PATH"
  script:
    - zig build
    
    - python3 -m pip install --upgrade pip
    - python3 -m pip install .
    
    - export PYTONGUE_TEST_BINARY=$CI_PROJECT_DIR/$BUILD_DIR/pytongue
    - touch $PYTONGUE_LOG
    - python3 -m pytest tests/e2e
    
    - echo "=== Test Logs ==="
    - cat $PYTONGUE_LOG
  artifacts:
    when: always
    paths:
      - $PYTONGUE_LOG
    expire_in: 1 week