image: archlinux

environment:
  PYTONGUE_LOG: /tmp/pytongue.log
  FORCE_COLOR: "1"
  ZIG_VERSION: 0.14.0


tasks:

  - setup:
      name: Install Dependencies
      script:
        - sudo pacman -Syu --noconfirm python python-pip wget tar gzip xz base-devel
        - python --version
        - pip --version

        - export ZIG_TARGET="x86_64-linux"
        - wget "https://ziglang.org/download/${ZIG_VERSION}/zig-linux-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz"

        - sudo mkdir -p /usr/local/lib/zig-${ZIG_VERSION}
        - sudo tar -xf "zig-linux-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz" -C /usr/local/lib/zig-${ZIG_VERSION}/ --strip-components=1
        - sudo ln -sf /usr/local/lib/zig-${ZIG_VERSION}/zig /usr/local/bin/zig
        - rm "zig-linux-${ZIG_TARGET}-${ZIG_VERSION}.tar.xz"

        - zig version

  - prepare:
      name: Navigate into project directory
      script:
        - cd Pytongue
        - pwd
        - ls -la

  - build:
      name: Build Zig project
      script:
        - cd Pytongue
        - zig build
        - ls -l zig-out/bin

  - install_python_deps:
      name: Install Python dependencies
      script:
        - cd Pytongue
        # Upgrade pip
        - python -m pip install --user --upgrade pip
        - python -m pip install --user
        - python -m pip install --user

  - test:
      name: Run e2e tests
      script:
        - cd pytongue
        - export PYTONGUE_TEST_BINARY="${PWD}/zig-out/bin/pytongue"
        - echo "Test binary path: ${PYTONGUE_TEST_BINARY}"
        - test -x "${PYTONGUE_TEST_BINARY}" || (echo "Test binary not found or not executable!" && exit 1)
        - export PATH=$PATH:/home/build/.local/bin
        - pytest tests/e2e

  - show_logs:
      name: Display test logs
      script:
        - echo "=== Test Logs (${PYTONGUE_LOG}) ==="
        - |
          if [ -f "${PYTONGUE_LOG}" ]; then
            cat "${PYTONGUE_LOG}"
          else
            echo "Log file ${PYTONGUE_LOG} not found."
          fi
