name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTONGUE_LOG: /tmp/pytongue.log
  BUILD_DIR: zig-out/bin

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: '0.13.0'

    - name: Build project
      run: zig build

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      env:
        # Assuming the binary name is the same as the project name
        # Modify the path according to your actual binary location and name
        PYTONGUE_TEST_BINARY: ${{ github.workspace }}/${{ env.BUILD_DIR }}/pytongue
      run: |
        touch ${{ env.PYTONGUE_LOG }}
        pytest tests/e2e
    - name: Print test logs
      if: success()
      run: |
        echo "=== Test Logs ==="
        cat ${{ env.PYTONGUE_LOG }}