# Decided that for now it's the best to have
# one job for build and test, might need to review
# this in the future.

name: Build and Test

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "tests/**"
      - "build.zig"
      - "build.zig.zon"
      - ".github/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "tests/**"
      - "build.zig"
      - "build.zig.zon"
  workflow_dispatch:

env:
  PYTONGUE_LOG: /tmp/pytongue.log
  BUILD_DIR: zig-out/bin
  FORCE_COLOR: 1

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: '0.14.0'

    - name: Build project
      run: zig build

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Run tests
      env:
        PYTONGUE_TEST_BINARY: ${{ github.workspace }}/${{ env.BUILD_DIR }}/pytongue
      run: |
        touch ${{ env.PYTONGUE_LOG }}
        pytest tests/e2e
    - name: Print test logs
      run: |
        echo "=== Test Logs ==="
        cat ${{ env.PYTONGUE_LOG }}
